apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-auger
spec:
  resources:
    - name: auger-repo
      type: git
    - name: auger-image
      type: image

  tasks:
    - name: build-auger
      taskRef:
        name: buildah
        kind: ClusterTask
      resources:
        inputs:
          - name: source
            resource: auger-repo
        outputs:
          - name: image
            resource: auger-image
      params:
        - name: TLSVERIFY
          value: "false"

    - name: apply-api-manifests
      taskRef:
        name: apply-manifests
      resources:
        inputs:
          - name: source
            resource: auger-repo
      runAfter:
        - build-auger

    - name: update-api-image
      taskRef:
        name: update-deployment
      resources:
        inputs:
          - name: image
            resource: auger-image
      params:
        - name: deployment
          value: "vauger-tbx"
      runAfter:
        - apply-api-manifests

