---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: auger-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/binliuk/auger.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: auger-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/go-https-pipeline/auger:latest

